"use server";
import {
    fetchUserContribution,getGithubToken
} from "@/module/github/lib/github";
import { auth } from "@/lib/auth";
import {headers} from "next/headers";
import { Octokit } from "octokit";
import prisma from "@/lib/db";


export async function getContributionStats(){
    try{
        const session=await auth.api.getSession({ headers: await headers() });
        if (!session?.user) {
            throw new Error("No session found");
        }
        const token = await getGithubToken();
        const octokit=new Octokit({
            auth:token
        });
        const {data:user}=await octokit.rest.users.getAuthenticated();
        const username=user.login;
        const calendar=await fetchUserContribution(token,username);
if (!calendar) {
    return {
        totalContributions: 0,
        contributions: []
    };
}
const contributions = calendar.weeks.flatMap((week: {
    contributionDays: {
        date: string;
        contributionCount: number;
    }[];
}) =>
    week.contributionDays.map((day: {
        date: string;
        contributionCount: number;
    }) => ({
        date: day.date,
        count: day.contributionCount,
        level:
    day.contributionCount === 0
        ? 0
        : day.contributionCount <= 2
            ? 1
            : day.contributionCount <= 5
                ? 2
                : day.contributionCount <= 10
                    ? 3
                    : 4
    }))
);
    return {
        contributions,
        totalContributions:calendar.totalContributions
    }
    }
    catch(error){
        console.error("Error fetching contribution stats:", error);
return {
    totalContributions: 0,
    contributions: []
};
    }
}
export async function getDashboardStats() {
    try {
        const session = await auth.api.getSession({
            headers: await headers()
        });

        if (!session?.user) {
            throw new Error("No session found");
        }

        const token = await getGithubToken();

        const octokit = new Octokit({
            auth: token
        });

        const { data: user } =
            await octokit.rest.users.getAuthenticated();

        // Connected repositories in CodeDive
const totalRepos = await prisma.repository.count({
  where: {
    userId: session.user.id,
    isConnected: true,
  },
});

        // Actual commits authored by the GitHub user
        const { data: commits } =
            await octokit.rest.search.commits({
                q: `author:${user.login}`,
                per_page: 1,
            });

        const totalCommits = commits.total_count;

        // Pull requests created by the user
        const { data: prs } =
            await octokit.rest.search.issuesAndPullRequests({
                q: `author:${user.login} type:pr`,
                per_page: 1,
            });

        const totalPRs = prs.total_count;

        // Reviews generated by CodeDive
        const totalReviews = await prisma.review.count({
            where: {
                repository: {
                    userId: session.user.id,
                },
            },
        });

        return {
            totalCommits,
            totalPRs,
            totalReviews,
            totalRepos,
        };

    } catch (error) {
        console.error(
            "Error fetching dashboard stats:",
            error
        );

        return {
            totalCommits: 0,
            totalPRs: 0,
            totalReviews: 0,
            totalRepos: 0,
        };
    }
}
export async function getMonthlyActivity() {
    try {
        const session = await auth.api.getSession({
            headers: await headers()
        });

        if (!session?.user) {
            throw new Error("No session found");
        }

        const token = await getGithubToken();

        const octokit = new Octokit({
            auth: token
        });

        const { data: user } =
            await octokit.rest.users.getAuthenticated();

        const calendar =
            await fetchUserContribution(token, user.login);

        if (!calendar) {
            return [];
        }

        const monthlyData: {
            [key: string]: {
                commits: number;
                prs: number;
                reviews: number;
            }
        } = {};

        const monthNames = [
            "Jan", "Feb", "Mar", "Apr",
            "May", "Jun", "Jul", "Aug",
            "Sep", "Oct", "Nov", "Dec"
        ];

        const now = new Date();

        // -----------------------------
        // Create last 6 months
        // -----------------------------
        for (let i = 5; i >= 0; i--) {
            const date = new Date(
                now.getFullYear(),
                now.getMonth() - i,
                1
            );

            const monthKey = monthNames[date.getMonth()];

            monthlyData[monthKey] = {
                commits: 0,
                prs: 0,
                reviews: 0
            };
        }

        // -----------------------------
        // Commits
        // -----------------------------
// -----------------------------
// Commits
// -----------------------------
const sixMonthsAgo = new Date();

sixMonthsAgo.setMonth(
    sixMonthsAgo.getMonth() - 6
);

const { data: commits } =
    await octokit.rest.search.commits({
        q: `author:${user.login} committer-date:>=${sixMonthsAgo
            .toISOString()
            .split("T")[0]}`,
        per_page: 100,
    });

commits.items.forEach((commit: {
    commit: {
        author?: {
            date?: string;
        };
    };
}) => {

    const commitDate = commit.commit.author?.date;

    if (!commitDate) return;

    const date = new Date(commitDate);

    const monthKey =
        monthNames[date.getMonth()];

    if (monthlyData[monthKey]) {
        monthlyData[monthKey].commits += 1;
    }
});

        // -----------------------------
        // Last 6 months date
        // -----------------------------

        // -----------------------------
        // REAL CODE REVIEWS
        // -----------------------------
        const reviews = await prisma.review.findMany({
            where: {
                repository: {
                    userId: session.user.id,
                },
                createdAt: {
                    gte: sixMonthsAgo,
                },
            },
            select: {
                createdAt: true,
            },
        });

        reviews.forEach((review) => {

            const monthKey =
                monthNames[review.createdAt.getMonth()];

            if (monthlyData[monthKey]) {
                monthlyData[monthKey].reviews += 1;
            }
        });

        // -----------------------------
        // Pull Requests
        // -----------------------------
        const { data: prs } =
            await octokit.rest.search.issuesAndPullRequests({
                q: `author:${user.login} type:pr created:>${sixMonthsAgo
                    .toISOString()
                    .split("T")[0]}`,
                per_page: 100,
            });

        prs.items.forEach((pr: {
            created_at: string;
        }) => {

            const date = new Date(pr.created_at);

            const monthKey =
                monthNames[date.getMonth()];

            if (monthlyData[monthKey]) {
                monthlyData[monthKey].prs += 1;
            }
        });

        // -----------------------------
        // Return chart data
        // -----------------------------
        return Object.keys(monthlyData).map((name) => ({
            name,
            ...monthlyData[name]
        }));

    } catch (error) {

        console.error(
            "Error fetching monthly activity:",
            error
        );

        return [];
    }
}